# https://github.com/localsend/localsend/blob/135939850291f6d15c984307cc9186f2ac5c9b36/.github/workflows/release.yml
# https://github.com/kra-mo/cartridges/blob/2801e777f785428614dab48cb6aa79068dc8ee67/.github/workflows/ci.yml

name: CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: release-${{ github.sha }}

jobs:
  build_tar_x86_64:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Dependencies
        run: flutter pub get

      - name: Compile Linux
        run: flutter build linux

      - name: Create tar.gz archive
        run: |
          cd build/linux/x64/release/bundle
          tar -czvf ../../../../../result.tar.gz *

      - name: Upload tar.gz archive
        uses: actions/upload-artifact@v4
        with:
          name: tar-gz-x86-64-result
          path: ./*.tar.gz

  build_windows_zip_x86_64:
    runs-on: windows-latest

    steps:
      - name: Fix long file paths
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Dependencies
        run: flutter pub get

      - name: Compile for Windows
        run: flutter build windows

      - name: Add DLL files
        run: |
          tree /F
          Copy-Item C:\\Windows\\System32\\msvcp140.dll build/windows/x64/runner/Release/
          Copy-Item C:\\Windows\\System32\\vcruntime140.dll build/windows/x64/runner/Release/
          Copy-Item C:\\Windows\\System32\\vcruntime140_1.dll build/windows/x64/runner/Release/

      - name: Zip compiled files
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath Sly.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip-x86-64-result
          path: Sly.zip
